# Introduction to numpy

numpy is a python library for vectors, matrices and general multidimensional arrays. It is highly optimized and therefore faster and more efficient than the python standard library. 

First you have to import numpy. A common convention is to import numpy as np.

In [1]:
import numpy as np

To create a numpy-array you first create a normal Python list an then convert via `np.array(list)` to a numpy-array.

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

Numpy-arrays can handle many types as Ints, Floats and Strings.

In [3]:
cvalues = [25.3, 24.8, 26.9, 23.9]
C = np.array(cvalues)

You can perform basic operations on numpy-arrays. In contrast to normal Python lists the operations are performed elementwise on the elements of the array. So to perform an operation on every element you don't have to iterate of the list or perform a list comprehension.

In [4]:
C * 9 / 5 + 32

array([77.54, 76.64, 80.42, 75.02])

In [5]:
[x * 9/5 + 32 for x in cvalues]

[77.54, 76.64, 80.42, 75.02]

## Werte mit gegebener Schrittweite erzeugen

arange([start, ] stop[, step,], dtype=None)

In [6]:
np.arange(3.0)

array([0., 1., 2.])

In [7]:
np.arange(1,5,2)

array([1, 3])

## Vergleich Python-Listen vs. Numpy-Arrays

In [8]:
import time

v = [e for e in range(10000)]

start = time.time()
for i in range(10000):
    x = [e+e for e in v]
    v = [e/2 for e in x]
time_lists = time.time() - start

arr = np.array(v)
start = time.time()
for i in range(10000):
    x = arr + arr
    arr = x/2
time_arrays = time.time() - start

print('time_list:', time_lists)
print('time_arrays:', time_arrays)

time_list: 7.512656211853027
time_arrays: 0.09043693542480469


## Arrays mit mehreren Achsen

In [9]:
np.array(42)

array(42)

In [10]:
np.array([3.4, 6.9, 99.8, 12.8])

array([ 3.4,  6.9, 99.8, 12.8])

In [11]:
np.array([[ 3.4,  8.7,  9.9 ], \
          [ 1.1, -7.8, -0.7 ], \
          [ 4.1, 12.3,  4.8 ]])

array([[ 3.4,  8.7,  9.9],
       [ 1.1, -7.8, -0.7],
       [ 4.1, 12.3,  4.8]])

In [12]:
np.array([[[ 111, 112 ], [ 121, 122 ]], \
          [[ 211, 212 ], [ 221, 222 ]], \
          [[ 311, 312 ], [ 321, 322 ]]])

array([[[111, 112],
        [121, 122]],

       [[211, 212],
        [221, 222]],

       [[311, 312],
        [321, 322]]])

## Shape eines Arrays

In [13]:
x = np.array([[67, 63, 87], \
              [77, 69, 59], \
              [77, 69, 59], \
              [67, 63, 87], \
              [67, 63, 87], \
              [67, 63, 87]])

np.shape(x)
x.shape # alternative.

(6, 3)

## Shape ändern

In [14]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
a.shape = (2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [16]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Transponieren

In [17]:
b = np.arange(6).reshape(2, 3)

print(b)
print(b.T)
b.transpose(1, 0)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

## Einfache Operatoren

In [18]:
n = np.array([20, 30, 40, 50])
p = np.array([0, 1, 2, 3])

In [19]:
n - p

array([20, 29, 38, 47])

In [20]:
p ** 2

array([0, 1, 4, 9])

In [21]:
n < 35

array([ True,  True, False, False])

In [22]:
n * p

array([  0,  30,  80, 150])

In [23]:
n.dot(p)  # np.dot(n, p)

260

## Unäre Operatoren

In [24]:
np.exp(p)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [25]:
np.sqrt(p)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [26]:
np.log(n)

array([2.99573227, 3.40119738, 3.68887945, 3.91202301])

## Summe, Maximum, Minimum

In [27]:
m = np.arange(12).reshape(3,4)

In [28]:
m.sum(axis=0)

array([12, 15, 18, 21])

In [29]:
m.min(axis=1)

array([0, 4, 8])

## Matrix-Multiplikation

In [30]:
X = np.array([[2, -1], [0, 3], [1, 0]])
Y = np.array([[2, 0], [1, -1]])

In [31]:
A = X.dot(Y) # np.dot(X, Y)
print(A)
print(A.shape)

[[ 3  1]
 [ 3 -3]
 [ 2  0]]
(3, 2)


## Elemente indizieren

In [32]:
B = np.array([[[ 111, 112 ], [ 121, 122 ]], \
              [[ 211, 212 ], [ 221, 222 ]], \
              [[ 311, 312 ], [ 321, 322 ]]])

In [33]:
print(B[2][1][0])

321


In [34]:
print(B[2, 1, 0])

321


In [35]:
print(B[1])

[[211 212]
 [221 222]]


In [36]:
print(B[-1, -1])

[321 322]


## Indizieren mit Index-Arrays/Listen

In [37]:
s = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5]) # i = [1, 1, 3, 8, 5]

In [38]:
s[i]

array([ 1,  1,  9, 64, 25])

## Indizieren mit Wahrheitswerten

In [39]:
g = np.arange(12).reshape(3, 4)

In [40]:
h = g > 4
print(h)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [41]:
g[h]

array([ 5,  6,  7,  8,  9, 10, 11])

In [42]:
g[h] = 0
print(g)

[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


## Slicing

In [43]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
S[3:6:2]

array([3, 5])

In [45]:
S[:4]

array([0, 1, 2, 3])

In [46]:
S[4:]

array([4, 5, 6, 7, 8, 9])

In [47]:
S[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Slicing (2 Achsen)

In [48]:
J = np.arange(25).reshape(5,5)

In [49]:
J[:3, 2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [50]:
J[3:, :]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
K = np.arange(28).reshape(4, 7)

In [52]:
K[::2, ::3]

array([[ 0,  3,  6],
       [14, 17, 20]])

In [53]:
K[:, ::3]

array([[ 0,  3,  6],
       [ 7, 10, 13],
       [14, 17, 20],
       [21, 24, 27]])

## View

In [54]:
D = np.arange(10)

In [55]:
V = D[2:6]

In [56]:
V[0] = 22

In [57]:
V[1] = 23

In [58]:
print(D)

[ 0  1 22 23  4  5  6  7  8  9]


In [59]:
Q = D[2:6].copy()

## Array aus Einsen/Nullen

In [60]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [62]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matrizen mit Zufallszahlen

In [63]:
np.random.rand(2,3)

array([[0.67729223, 0.10625686, 0.14852631],
       [0.56415916, 0.0735136 , 0.93470977]])

In [64]:
np.random.randn(2,3)

array([[ 0.10498602,  0.71677516, -0.4101949 ],
       [ 0.85950721, -0.07513631,  0.43383245]])

## Iterieren

In [65]:
for row in np.arange(12).reshape(3,4):
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


## Stacking von Arrays

In [66]:
e = np.array([[1,2], [3,4]])
r = np.array([[11, 22], [33, 44]])

In [67]:
np.vstack((e,r))

array([[ 1,  2],
       [ 3,  4],
       [11, 22],
       [33, 44]])

In [68]:
np.hstack((e,r))

array([[ 1,  2, 11, 22],
       [ 3,  4, 33, 44]])