# Introduction to numpy

numpy is a python library for vectors, matrices and general multidimensional arrays. It is highly optimized and therefore faster and more efficient than the python standard library. 

First you have to import numpy. A common convention is to import numpy as np.

In [95]:
import numpy as np

In [96]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [97]:
cvalues = [25.3, 24.8, 26.9, 23.9]
C = np.array(cvalues)

In [98]:
C * 9 / 5 + 32

array([77.54, 76.64, 80.42, 75.02])

In [99]:
[x * 9/5 + 32 for x in cvalues]

[77.54, 76.64, 80.42, 75.02]

arange([start, ] stop[, step,], dtype=None)

In [100]:
np.arange(3.0)

array([0., 1., 2.])

In [101]:
np.arange(1,5,2)

array([1, 3])

In [102]:
import time

v = [e for e in range(10000)]

start = time.time()
for i in range(10000):
    x = [e+e for e in v]
    v = [e/2 for e in x]
time_lists = time.time() - start

arr = np.array(v)
start = time.time()
for i in range(10000):
    x = arr + arr
    arr = x/2
time_arrays = time.time() - start

print('time_list:', time_lists)
print('time_arrays:', time_arrays)

time_list: 7.466540813446045
time_arrays: 0.09273982048034668


In [103]:
np.array(42)

array(42)

In [104]:
np.array([3.4, 6.9, 99.8, 12.8])

array([ 3.4,  6.9, 99.8, 12.8])

In [105]:
np.array([[ 3.4,  8.7,  9.9 ], \
          [ 1.1, -7.8, -0.7 ], \
          [ 4.1, 12.3,  4.8 ]])

array([[ 3.4,  8.7,  9.9],
       [ 1.1, -7.8, -0.7],
       [ 4.1, 12.3,  4.8]])

In [106]:
np.array([[[ 111, 112 ], [ 121, 122 ]], \
          [[ 211, 212 ], [ 221, 222 ]], \
          [[ 311, 312 ], [ 321, 322 ]]])

array([[[111, 112],
        [121, 122]],

       [[211, 212],
        [221, 222]],

       [[311, 312],
        [321, 322]]])

In [107]:
x = np.array([[67, 63, 87], \
              [77, 69, 59], \
              [77, 69, 59], \
              [67, 63, 87], \
              [67, 63, 87], \
              [67, 63, 87]])

np.shape(x)
x.shape # alternative.

(6, 3)

In [108]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [109]:
a.shape = (2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [110]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [111]:
b = np.arange(6).reshape(2, 3)

print(b)
print(b.T)
b.transpose(1, 0)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

In [112]:
n = np.array([20, 30, 40, 50])
p = np.array([0, 1, 2, 3])

In [113]:
n - p

array([20, 29, 38, 47])

In [114]:
p ** 2

array([0, 1, 4, 9])

In [115]:
n < 35

array([ True,  True, False, False])

In [116]:
n * p

array([  0,  30,  80, 150])

In [117]:
n.dot(p)  # np.dot(n, p)

260

In [118]:
np.exp(p)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [119]:
np.sqrt(p)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [120]:
np.log(n)

array([2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [121]:
m = np.arange(12).reshape(3,4)

In [122]:
m.sum(axis=0)

array([12, 15, 18, 21])

In [123]:
m.min(axis=1)

array([0, 4, 8])

## Matrix-Multiplikation

In [124]:
X = np.array([[2, -1], [0, 3], [1, 0]])
Y = np.array([[2, 0], [1, -1]])

In [125]:
A = X.dot(Y) # np.dot(X, Y)
print(A)
print(A.shape)

[[ 3  1]
 [ 3 -3]
 [ 2  0]]
(3, 2)


## Elemente indizieren

In [126]:
B = np.array([[[ 111, 112 ], [ 121, 122 ]], \
              [[ 211, 212 ], [ 221, 222 ]], \
              [[ 311, 312 ], [ 321, 322 ]]])

In [127]:
print(B[2][1][0])

321


In [128]:
print(B[2, 1, 0])

321


In [129]:
print(B[1])

[[211 212]
 [221 222]]


In [130]:
print(B[-1, -1])

[321 322]


## Indizieren mit Index-Arrays/Listen

In [131]:
s = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5]) # i = [1, 1, 3, 8, 5]

In [132]:
a[i]

IndexError: index 3 is out of bounds for axis 0 with size 2

## Indizieren mit Wahrheitswerten

In [ ]:
g = np.arange(12).reshape(3, 4)

In [ ]:
h = g > 4
print(h)

In [ ]:
g[h]

In [ ]:
g[h] = 0
print(g)

## Slicing

In [ ]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
S[3:6:2]

In [ ]:
S[:4]

In [ ]:
S[4:]

In [ ]:
S[:]

## Slicing (2 Achsen)

In [ ]:
J = np.arange(25).reshape(5,5)

In [ ]:
J[:3, 2:]

In [ ]:
J[3:, :]

In [ ]:
K = np.arange(28).reshape(4, 7)

In [ ]:
K[::2, ::3]

In [ ]:
K[:, ::3]

## View

In [ ]:
D = np.arange(10)

In [ ]:
V = D[2:6]

In [ ]:
V[0] = 22

In [ ]:
V[1] = 23

In [ ]:
print(D)

In [ ]:
Q = D[2:6].copy()

## Array aus Einsen/Nullen

In [ ]:
np.ones((2,3))

In [ ]:
np.ones((3,4), dtype=int)

In [ ]:
np.zeros((2,4))

## Matrizen mit Zufallszahlen

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.randn(2,3)

## Iterieren

In [ ]:
for row in np.arange(12).reshape(3,4):
    print(row)

## Stacking von Arrays

In [ ]:
e = np.array([[1,2], [3,4]])
r = np.array([[11, 22], [33, 44]])

In [ ]:
np.vstack((e,r))