# Introduction to numpy

numpy is a python library for vectors, matrices and general multidimensional arrays. It is highly optimized and therefore faster and more efficient than the python standard library. 

First you have to import numpy. A common convention is to import numpy as np.

In [63]:
import numpy as np

In [64]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [65]:
cvalues = [25.3, 24.8, 26.9, 23.9]
C = np.array(cvalues)

In [66]:
C * 9 / 5 + 32

array([77.54, 76.64, 80.42, 75.02])

In [67]:
[x * 9/5 + 32 for x in cvalues]

[77.54, 76.64, 80.42, 75.02]

arange([start, ] stop[, step,], dtype=None)

In [68]:
np.arange(3.0)

array([0., 1., 2.])

In [69]:
np.arange(1,5,2)

array([1, 3])

In [70]:
import time

v = [e for e in range(10000)]

start = time.time()
for i in range(10000):
    x = [e+e for e in v]
    v = [e/2 for e in x]
time_lists = time.time() - start

arr = np.array(v)
start = time.time()
for i in range(10000):
    x = arr + arr
    arr = x/2
time_arrays = time.time() - start

print('time_list:', time_lists)
print('time_arrays:', time_arrays)

time_list: 13.626914262771606
time_arrays: 0.2525150775909424


In [71]:
np.array(42)

array(42)

In [72]:
np.array([3.4, 6.9, 99.8, 12.8])

array([ 3.4,  6.9, 99.8, 12.8])

In [73]:
np.array([[ 3.4,  8.7,  9.9 ], \
          [ 1.1, -7.8, -0.7 ], \
          [ 4.1, 12.3,  4.8 ]])

array([[ 3.4,  8.7,  9.9],
       [ 1.1, -7.8, -0.7],
       [ 4.1, 12.3,  4.8]])

In [74]:
np.array([[[ 111, 112 ], [ 121, 122 ]], \
          [[ 211, 212 ], [ 221, 222 ]], \
          [[ 311, 312 ], [ 321, 322 ]]])

array([[[111, 112],
        [121, 122]],

       [[211, 212],
        [221, 222]],

       [[311, 312],
        [321, 322]]])

In [75]:
x = np.array([[67, 63, 87], \
              [77, 69, 59], \
              [77, 69, 59], \
              [67, 63, 87], \
              [67, 63, 87], \
              [67, 63, 87]])

np.shape(x)
x.shape # alternative.

(6, 3)

In [76]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [77]:
a.shape = (2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [78]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [79]:
b = np.arange(6).reshape(2, 3)

print(b)
print(b.T)
b.transpose(1, 0)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

In [80]:
n = np.array([20, 30, 40, 50])
p = np.array([0, 1, 2, 3])

In [81]:
n - p

array([20, 29, 38, 47])

In [82]:
p ** 2

array([0, 1, 4, 9])

In [83]:
n < 35

array([ True,  True, False, False])

In [84]:
n * p

array([  0,  30,  80, 150])

In [85]:
n.dot(p)  # np.dot(n, p)

260

In [86]:
np.exp(p)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [87]:
np.sqrt(p)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [89]:
np.log(n)

array([2.99573227, 3.40119738, 3.68887945, 3.91202301])